cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', views.cart_remove, name='cart_remove'),
    url(r'^add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add')
]

cupon/urls.py
from django.conf.urls import url

from . import views

app_name = 'cupon'
urlpatterns = [
        url(r'^apply/$', views.cupon_apply, name='cupon_apply'),
        ]

orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^create/$', views.create_order, name='create_order'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf')
]

recycleProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include("cart.urls", namespace="cart")),
    url(r'^order/', include("orders.urls", namespace="orders")),
    url(r'^cupon/', include("cupon.urls", namespace="cupon")),
    url(r'^api/v0/', include('api_v0.urls', namespace="api")),
    url(r'^blog/', include('news.urls', namespace="blog")),
    url(r'^', include('shopRecycle.urls', namespace="shopRecycle")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^auth/', include('core.urls', namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopRecycle/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopRecycle'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^product_list/$', views.product_list, name='product_list'),
    url(r'^(?P<category_name>\w+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<product_id>[0-9]+)/detail/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    count = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shopRecycle.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cupon.form import CuponForm
import sys

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, quantity=cd["count"],
                 update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(initial={"count": item["count"],
                                                                   "update": True})
    cupon_form = CuponForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'cupon_form': cupon_form})

cart/templates/cart/detail.html
{% extends "recycleShop/base.html" %}
{% block title %}
  Basket of goods
{% endblock %}
{% block content %}
  <h1>Basket of goods</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Count</th>
        <th>Remove</th>
        <th>Total price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.product_name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">{% csrf_token %}
                {{ item.update_quantity_form.count }}
                {{ item.update_quantity_form.update }}
              <input type="submit" value="Update">
        </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            <td class="num">{{ item.price }} грн.</td>
            <td class="num">{{ item.total_price }} грн.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        {% if cart.cupon %}
          <tr class="subtotal">
            <td>Price without discount</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }}</td>
          </tr>
          <tr>
            <td>
              "{{ cart.cupon.code }}" cupon for ({{ cart.cupon.discount }} %)
            </td>
            <td colspan="4"></td>
            <td class="num discount"> - {{ cart.get_discount|floatformat:"2" }} грн.</td>
          </tr>
        {% endif %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} грн.</td>
        </tr>
    </tbody>
  </table>

  <p>Apply cupon</p>
  <form action="{% url 'cupon:cupon_apply' %}" method="post" class="add">
    {% csrf_token %}
    {{ cupon_form }}
    <input type="submit" value="Update">
  </form>
  <p class="text-right">
    <a href="{% url 'shopRecycle:product_list'%}" class="btn">Return to products list</a>
    <a href="{% url 'orders:create_order'%}" class="btn">Create order</a>
  </p>
{% endblock %}