cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', views.cart_remove, name='cart_remove'),
    url(r'^add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add')
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.update_profile, name='update_profile'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                views.activate, name='activate'),
]

recycleProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include("cart.urls", namespace="cart")),
    url(r'^order/', include("orders.urls", namespace="orders")),
    url(r'^cupon/', include("cupon.urls", namespace="cupon")),
    url(r'^api/v0/', include('api_v0.urls', namespace="api")),
    url(r'^blog/', include('news.urls', namespace="blog")),
    url(r'^', include('shopRecycle.urls', namespace="shopRecycle")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^auth/', include('core.urls', namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopRecycle/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopRecycle'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^product_list/$', views.product_list, name='product_list'),
    url(r'^(?P<category_name>\w+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<product_id>[0-9]+)/detail/$', views.product_detail, name='product_detail'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    email_confirmed = models.BooleanField(default=False)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    city = forms.CharField(max_length=30, required=False, help_text='Optional.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'city', 'birth_date')


class UserUpdateForm(forms.ModelForm):

    email = forms.EmailField(max_length=254)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    city = forms.CharField(max_length=30, required=False, help_text='Optional.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'city', 'birth_date')

core/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from .forms import SignUpForm, UserUpdateForm
from .tokens import account_activation_token

@login_required
def home(request):
    return render(request, 'home.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Kosatka Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode("utf-8"),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('core:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('core:home')
    else:
        return render(request, 'account_activation_invalid.html')


@login_required
def profile(request):
    user = request.user
    return render(request, "user_profile.html", {"user": user})


@login_required
def update_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserUpdateForm(request.POST)
        if form.is_valid():
            user.email = form.cleaned_data.get("email", user.email)
            user.first_name = form.cleaned_data.get("first_name", user.first_name)
            user.last_name = form.cleaned_data.get("last_name", user.last_name)
            user.profile.birth_date = form.cleaned_data.get("birth_date", user.profile.birth_date)
            if form.cleaned_data.get("password") is not None:
                user.set_password(form.cleaned_data.get("password"))
            return redirect('core:profile')
    else:
        form = UserUpdateForm(instance=user)
    return render(request, 'profile_edit.html', {'form': form})

core/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'core:activate' uidb64=uid token=token %}
{% endautoescape %}

core/templates/account_activation_invalid.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

core/templates/account_activation_sent.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

core/templates/home.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Thanks for confirming your email address!</p>
  <a href="{% url 'shopRecycle:main' %}"></a>
{% endblock %}

core/templates/login.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'core:signup' %}">New to Kosatka? Sign up</a>
  </form>
{% endblock %}

core/templates/profile_edit.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

core/templates/signup.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

core/templates/user_profile.html
{% extends 'recycleShop/base.html' %}

{% block content %}
  <h2>User profilep</h2>
  <div class="user_profile">
      <ul>
          <li>Username: {{user.username}}</li>
          <li>Email: {{user.email}}</li>
          <li>First Name: {{user.first_name}}</li>
          <li>Last Name: {{user.last_name}}</li>
          <li>City: {{user.city}}</li>
          <li>Birth date: {{user.profile.birth_date}}</li>
      </ul>
      <a href="{% url 'core:update_profile' %}">Edit</a>
  </div>
{% endblock %}