cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', views.cart_remove, name='cart_remove'),
    url(r'^add/(?P<product_id>[0-9]+)/$', views.cart_add, name='cart_add')
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.update_profile, name='update_profile'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                views.activate, name='activate'),
]

news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
        url(r'^all/$', views.posts_list, name='posts_list'),
        url(r'^blog_detail/(?P<blog_id>\d+)/$', views.post_details, name='post_details'),
        ]

recycleProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include("cart.urls", namespace="cart")),
    url(r'^order/', include("orders.urls", namespace="orders")),
    url(r'^cupon/', include("cupon.urls", namespace="cupon")),
    url(r'^api/v0/', include('api_v0.urls', namespace="api")),
    url(r'^blog/', include('news.urls', namespace="blog")),
    url(r'^', include('shopRecycle.urls', namespace="shopRecycle")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^auth/', include('core.urls', namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopRecycle/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopRecycle'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^product_list/$', views.product_list, name='product_list'),
    url(r'^(?P<category_name>\w+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<product_id>[0-9]+)/detail/$', views.product_detail, name='product_detail'),
]

shopRecycle/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=200)
    category_description = models.CharField(max_length=200)

    def __str__(self):
        return self.category_name

    def get_abs_url(self):
        return reverse("shopRecycle:product_list_by_category", args=[self.category_name])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    product_name = models.CharField(max_length=200)
    product_description = models.CharField(max_length=200)
    added_date = models.DateTimeField("pub date")
    price = models.FloatField()
    count = models.IntegerField()
    color = models.TextField(choices=[("GR", "green"),("BL", "blue"),("WT", "white"),("BL", "black")])
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True)
    should_be_on_main = models.BooleanField(default=False)

    def is_available(self):
        return self.count > 0

    def __str__(self):
        return self.product_name

    def get_abs_url(self):
        return reverse("shopRecycle:product_detail", args=[self.id])

shopRecycle/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from news.models import NewPost


def main(request):
    main_products = Product.objects.filter(should_be_on_main=True)
    blogs = NewPost.objects.all().order_by("pub_date")[:2]
    categories = Category.objects.all()
    return render(request,'recycleShop/main.html', {"main_products": main_products, "blogs": blogs, "categories": categories})

def product_list(request, category_name=None):
    if category_name is None:
        all_products = Product.objects.all()
        category = None
    else:
        category = get_object_or_404(Category, category_name=category_name)
        all_products = category.products.all()
    categories = Category.objects.all()
    return render(request, 'recycleShop/products.html', {
        'category': category,
        'categories': categories,
        'all_products': all_products
    })


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart_product_form = CartAddProductForm()
    return render(request, 'recycleShop/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})

shopRecycle/templates/recycleShop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- Styles -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block js-head %}{% endblock js-head %}
</head>
<body>
  <section id="header">
    <div class="top container">
      <h2><a href="{% url 'shopRecycle:main' %}">Recycle Shop</a></h2>
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
          {% if cart|length  > 0 %}
            <a href="{% url 'cart:cart_detail' %}">
              {{ cart|length  }} items {{ cart.get_total_price }} грн.
            </a>
          {% else %}
            Empty basket
          {% endif %}
        </div>
        <div class="login_main">
          {% if user.is_authenticated %}
            <p>{{ user.username }}</p>
            <a href="{% url 'core:logout' %}?next={{ request.path | urlencode }}">logout</a>
          {% else %}
            <a href="{% url 'core:login' %}">login</a> / <a href="{% url 'core:signup' %}">signup</a>
      {% endif %}
        </div>
      </div>
    </div>
  </section>
  <section id="content-row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

shopRecycle/templates/recycleShop/detail.html
{% extends 'recycleShop/base.html' %}
{% load static %}
{% block title %}
    {{ product.product_name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <div class="col-sm-4">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}" class="img-responsive">
        </div>
    <div class="col-sm-8">
      <h1>{{ product.product_name }}</h1>
      <h2><a href="{{ product.category.get_abs_url }}">{{ product.category }}</a></h2>
      <p class="price">{{ product.price }} грн.</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">{% csrf_token %}
            {{ cart_product_form }}
        <input type="submit" value="Add to basket">
        </form>
      <span>
        {{ product.description | linebreaks}}
      </span>
        <span> Available {{ product.count }} </span>
    </div>
  </div>
{% endblock %}

shopRecycle/templates/recycleShop/main.html
{% extends 'recycleShop/base.html' %}
{% load static %}
{% block title %}
  Kosatka Recycle Shop
{% endblock %}
{% block content %}
    <div class="navbar-categories">
        {% for category in categories %}
        <div class="dropdown">
            <a href="{% url 'shopRecycle:product_list_by_category' category_name=category.category_name %}"><button class="dropbtn">{{ category.category_name }}</button></a>
        </div>
        {% endfor %}
    </div>
    <h1>Top products</h1>

    <div class="top_products row">
        {% for prod in main_products %}
        <div class="prod_item">
          <a class="product_image" href="{{ product.get_abs_url }}">
            <img src="{% if prod.image %}{{ prod.image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}" class="img-responsive">
          </a>
          <a class="product_link" href="{{ prod.get_abs_url }}">{{ prod.product_name }}</a><br>
          {{ prod.price }} грн.
        </div>
        {% endfor %}
    </div>

    <h1>Blog</h1>

    <div class="top_blogs">
        {% for blog in blogs %}
        <div class="blog_item">
            <a class="blog_image" href="{{ blog.get_abs_url }}">
                <img src="{% if blog.short_image %}{{ blog.short_image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}" class="img-responsive">
            </a>
            <a class="blog_link" href="{{ blog.get_abs_url }}">{{ blog.title }}</a>
            <p>{{ blog.short_description }}</p>
        </div>
        {% endfor %}
        <a class="blog_details_btn" href="{% url 'news:posts_list' %}">Read More...</a>
    </div>
{% endblock %}

shopRecycle/templates/recycleShop/products.html
{% extends 'recycleShop/base.html' %}
{% load static %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} All products list {% endif %}
{% endblock %}
{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'shopRecycle:product_list' %}">All</a>
      </li>
      {% for cat in categories %}
        <li {% if category.category_name == cat.category_name %} class="selected" {% endif %}>
            <a href="{{ cat.get_abs_url }}">{{ cat.category_name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.category_name }}{% else %}All products{% endif %}</h1>
    <div class="items row">
      {% for product in all_products %}
        <div class="item col-sm-4">
          <a class="product_image" href="{{ product.get_abs_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}" class="img-responsive">
          </a>
          <a class="product_link" href="{{ product.get_abs_url }}">{{ product.product_name }}</a><br>
          {{ product.price }} грн.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}</code>
</pre>